### ISSUE TITLE
LinkGenerator is prepending contextPath 2x

### ISSUE THREAD

**Issue by krond** [bertramdev/grails-asset-pipeline#312]
We recently upgraded the asset pipeline plugin from version 2.5.2 to 2.6.2 and discovered that the resolution of assets with the grailsLinkGenerator (e.g. used through the resource tag) doesn't work as expected any more.

In version 2.5.2 of the plugin, the resulting link is generated correctly: /myApp/assets/customer/mail-header.jpg
In version 2.6.2, the context path is duplicated: /myApp/myApp/assets/customer/mail-header.jpg

I have tested this behavior with the following example code:

	class TestController {
		
		def grailsLinkGenerator
		
		def test() {
			render grailsLinkGenerator.resource(src: 'customer/mail-header.jpg')
		}
	}

In Config.groovy the serverURL is configured as follows:

	grails.serverURL = "http://localhost:8080/myApp"

Edit: we are using grails version 2.5.1

**Comment by longwa** [comment]
We are seeing the same behavior. I created a simple test app that renders the grails_logo.png on the index.gsp.

https://github.com/longwa/grails3-asset-url

If you hit:

http://localhost:8080/myapplication/

You will see the issue. The `assetBaseUrl` is including the contextPath already but then the absolute link logic is also adding it again.

**Comment by rgoldberg** [comment]
I can't reproduce this in dev mode using AP 2.6.10 on Grails 2.5.3.

The following call (in `BootStrap.groovy`) returned a URL that only contained the context path once:

    grailsLinkGenerator.resource(src: 'social/addthis.png')

Returned:

    http://localhost:8080/myApp/assets/social/addthis.png

I tried it both with just the following in `Config.groovy`:

    grails.serverURL = 'http://localhost:8080/myApp'

And with both the following in `Config.groovy`:

    grails.app.context = 'myApp'
    grails.serverURL = 'http://localhost:8080/myApp'

**Comment by krond** [comment]
I tried again with Grails 2.5.3 and AP 2.6.10 and I can reproduce the bug in all combinations of dev/prod and run-app/run-war.

**Comment by rgoldberg** [comment]
I'll try this sometime later in the week.

Once I have free time, it shouldn't be too hard to debug & fix, given your reproduction instructions.

**Comment by rgoldberg** [comment]
Fixed in PR #316

**Comment by zyro23** [comment]
no chance for a 2.6.11? or is 2.7.0 around the corner anyway?
facing this after asset-pipeline update to 2.6.10 with plugins using the resource tag (e.g. quartz-monitor)

**Comment by amedlock** [comment]
I am seeing this on an application while I am porting a grails application from 2.3.11 -> 3.1.1

I set the context path in application.yml:  
server:
   contextPath: "/myapp"

And using the resource(...)  all my images uri s look like:

"/myApp/myApp/images/myimage.gif"

If I remove the contextPath from the application the images are referenced correctly but removing the context Path at this point isn't feasible.

**Comment by davydotcom** [comment]
fixed in 2.7.0 or 3.1.0 for grails3

**Comment by cwack-letsdev** [comment]
I still have this issue in following version:

| Grails Version: 3.1.0
| Groovy Version: 2.4.5
| JVM Version: 1.8.0_65
